config/routes.rb
Rails.application.routes.draw do

  root "static_pages#index"

  resources :stores do 
    resources :products
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :store
end

app/models/store.rb
class Store < ActiveRecord::Base
	has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		@products = Product.all
	end

	def new
		@product = Product.new
		@store = Store.find(params[:store_id])
	end

	def create
		@store = Store.find(params[:store_id])
		@product = @store.products.build(product_params)
		@product.save
		redirect_to @store # Rather redirect to the actual product created.
	end

	def show
		@product = Product.find(params[:id])
	end

	private

		def product_params
			params.require(:product).permit(:name, :description, :price)
		end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
	end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

	def index
		@stores = Store.all
	end

	def new
		@store = Store.new
	end

	def create
		@store = Store.create(params[:store].permit(:city, :state))
		redirect_to @store
	end

	def show
		@store = Store.find(params[:id])
		@products = Product.where(store_id: @store.id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hockey Stores</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div>
		<%= link_to "Home", root_path %> - 
		<%= link_to "Stores", stores_path %>
	</div>

	<%= yield %>

</body>
</html>

app/views/products/new.html.erb
<h1>Add Product to <%= "#{@store.city}, #{@store.state}" %> Store</h1>

<%#= form_for @product, url: {action: "create"} do |f| %>
<%= form_for([@store, @product]) do |f| %> <!-- Why on products do I need [@store, @product]? -->
	<p><%= f.label(:name) %><br />
	<%= f.text_field(:name) %></p>
	<p><%= f.label(:description) %><br />
	<%= f.text_field(:description) %></p>
	<p><%= f.label(:price) %><br />
	<%= f.text_field(:price) %></p>

	<%= submit_tag("Add Product") %>
<% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<p><%= @product.description %></p>

<p>Price: $<%= @product.price %></p>

app/views/static_pages/index.html.erb
<h1>Welcome to the Hockey Store!</h1>

<p>Check out our list of <%= link_to "stores", stores_path %></p>

app/views/stores/index.html.erb
<h1>All Hockey Stores</h1>

<p>Visit the store closest to you to see available products.<br />
<%= link_to "Add Store", new_store_path %></p>

<% @stores.each do |store| %>
	<div class="store">
		<p><%= link_to "#{store.city}, #{store.state}", store_path(store.id) %></p>
	</div>
<% end %>

app/views/stores/new.html.erb
<h1>Add Hockey Store</h1>

<%= form_for(@store) do |f| %>
	<p><%= f.label(:city) %><br />
	<%= f.text_field(:city) %></p>
	<p><%= f.label(:state) %><br />
	<%= f.text_field(:state) %></p>

	<%= submit_tag("Add Store") %>
<% end %>

app/views/stores/show.html.erb
<h1><%= "#{@store.city}, #{@store.state} Store" %></h1>

<p>Click on any of the products to see more details.<br />
<%= link_to "Add Product", new_store_product_path(@store) %></p>

<% @products.each do |product| %>
	<div class="product">
		<p><%= link_to "#{product.name}", store_product_path(@store, product) %></p>
	</div>
<% end %>